# Generated by Django 3.2.22 on 2023-11-12 11:09

from django.db import migrations
from django.contrib.auth import get_user_model


User = get_user_model()


def add_chats(apps, schema_editor):
    # We can't import Group model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Chat = apps.get_model("chat", "Group")
    Chat.objects.get_or_create(chatname='Sport')
    Chat.objects.get_or_create(chatname='Games')
    Chat.objects.get_or_create(chatname='Films')


def add_messages(apps, schema_editor):
    # We can't import Group model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Message = apps.get_model("chat", "Message")
    Message.objects.get_or_create(author=1, content="Hello Sport chat", group=1)
    Message.objects.get_or_create(author=2, content="Hello Games chat", group=2)
    Message.objects.get_or_create(author=3, content="Hello Films chat", group=3)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_timestamp'),
    ]

    operations = [
        migrations.RunPython(add_chats),
        migrations.RunPython(add_messages),
    ]
